name: "Verify PR"

on:
  pull_request:

jobs:
  verify:
    name: Verify PR
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4.3.1
      - name: Validate Action
        uses: meza/action-validate-action@v1.0.1
